/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.rumah.sakit.lekas.sehat;

import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Alfianda Syahrul
 */
public class Antrianku extends javax.swing.JFrame {
    
    String pol, tgl, no, usiaa;

    /**
     * Creates new form Produk
     */
    public Antrianku() {
        initComponents();
        loadTabelAntrian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAntrian = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 400));
        setResizable(false);

        tbAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAntrian);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari tujuan poli :");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCari))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah)
                        .addComponent(btnHapus)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCari)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        Antrian antrian = new Antrian();
        dispose();
        antrian.setVisible(true);
        antrian.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnTambahActionPerformed
    
    int selectedID;
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if(tbAntrian.isRowSelected(tbAntrian.getSelectedRow())==true){
            selectedID = (int)tbAntrian.getValueAt(tbAntrian.getSelectedRow(), 0);
            
            int result = JOptionPane.showConfirmDialog(this,
                    "Kamu akan menghapus data "
                    + tbAntrian.getValueAt(tbAntrian.getSelectedRow(), 1).toString(),
                    "Peringatan!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try{
                    PreparedStatement stmt = conn.prepareStatement("DELETE FROM antrian WHERE id=?");
                    stmt.setInt(1, selectedID);
                    stmt.executeUpdate();
                    loadTabelAntrian();
                }catch(SQLException e){
                    System.out.println(e.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tidak ada yang dipilih");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        if(evt.getKeyChar()>='a'&&evt.getKeyChar()<='z' ||
                evt.getKeyChar()>='A'&&evt.getKeyChar()<='Z' ||
                evt.getKeyCode() == java.awt.event.KeyEvent.VK_SPACE ||
                evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
                txtCari.setEditable(true);
//                String teks = txtCari.getText();
//                loadTabelAntrian(teks);
        } else if(evt.getKeyCode()== KeyEvent.VK_ENTER){
                    String teks = txtCari.getText();
                    loadTabelAntrian(teks);
        }else {
            txtCari.setEditable(false);
        }
    }//GEN-LAST:event_txtCariKeyPressed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String teks = txtCari.getText();
        loadTabelAntrian(teks);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if(tbAntrian.isRowSelected(tbAntrian.getSelectedRow())==true){
            selectedID = (int)tbAntrian.getValueAt(tbAntrian.getSelectedRow(), 0);
            
            int result = JOptionPane.showConfirmDialog(this,
                    "Cetak bukti antrian"
                    + tbAntrian.getValueAt(tbAntrian.getSelectedRow(), 1).toString(),
                    "Pemberitahuan!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try{
                    PreparedStatement stmt = conn.prepareStatement("SELECT * FROM antrian WHERE id=?");
                    stmt.setInt(1, selectedID);
                    ResultSet rs = stmt.executeQuery();
                    if (rs.next()) {
                        pol = (rs.getString("spesialis"));
                        no = (rs.getString("no_antri"));
                        tgl = (rs.getString("tanggal"));
                    }
                    usia();
                }catch(SQLException e){
                    System.out.println(e.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tidak ada yang dipilih");
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antrianku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antrianku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antrianku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antrianku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antrianku().setVisible(true);
            }
        });
    }
    
    Connection conn = Koneksi.connectDB();
    public void loadTabelAntrian(){
        String sql = "SELECT * FROM antrian WHERE nrm=? ORDER BY tanggal";
        Object[] kolom = { "ID", "Poli Tujuan", "Tanggal", "Nomor Antrian"};
        DefaultTableModel dataModel = new DefaultTableModel (null, kolom);
        tbAntrian.setModel(dataModel);
        tbAntrian.getColumnModel().getColumn(0).setMaxWidth(30);
        
        try{
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, Utama.NRM);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                int id = rs.getInt("id");
                String poli = rs.getString("spesialis");
                String tanggal = rs.getString("tanggal");
                String nomor = rs.getString("no_antri");
                
                Object[] data = {id, poli, tanggal, nomor};
                dataModel.addRow(data);
            }
            
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    public void loadTabelAntrian(String teks){
        String sql = "SELECT * FROM antrian WHERE nrm=? AND spesialis like ? ORDER BY tanggal";
        Object[] kolom = { "ID", "Poli Tujuan", "Tanggal", "Nomor Antrian"};
        DefaultTableModel dataModel = new DefaultTableModel (null, kolom);
        tbAntrian.setModel(dataModel);
        tbAntrian.getColumnModel().getColumn(0).setMaxWidth(30);
        
        try{
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, Utama.NRM);
            stmt.setString(2, teks);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                int id = rs.getInt("id");
                String poli = rs.getString("spesialis");
                String tanggal = rs.getString("tanggal");
                String nomor = rs.getString("no_antri");
                
                Object[] data = {id, poli, tanggal, nomor};
                dataModel.addRow(data);
            }
            
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    public void usia() {
        LocalDate lahir = LocalDate.parse(Utama.TAHUN);
        LocalDate now = LocalDate.now();
        Period usia = Period.between(lahir, now);
        usiaa = String.valueOf(usia.getYears());
        cetak();
    }
    
    public void cetak(){        
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("NRM", Utama.NRM);
        parameters.put("NAMA", Utama.NAMA);
        parameters.put("USIA", usiaa);
        parameters.put("JENIS", Utama.JENIS);
        parameters.put("POLI", pol);
        parameters.put("NOMOR", no);
        parameters.put("TGL", tgl);
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass()
                    .getResourceAsStream("../../../../../cetak/cetakNomor.jasper"), 
                    parameters, conn);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAntrian;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

}
